### PR TITLE
Cross platform npm scripts

### PR DESCRIPTION
**Pull request by RobertSandu**
As requested, I created another pull request.

### CODE REVIEW

**Comment by robert-sandu** [comment]
And I confirm again that I am ok with this pull request

**Comment by RobertSandu** [comment]
Done

**Comment by RobertSandu** [comment]
@saeidalidadi what failure?

**Comment by saeidalidadi** [comment]
@RobertSandu the CI checks

**Comment by nicolodavis** [comment]
It's possible that the CLA bot blocks the other CI checks. I'll verify this manually sometime closer to the weekend. Thanks for the PR, Robert!

**Comment by clarkjoseph00** [comment]
Sure wish someone would help me

**Pull request merged**
