### PR TITLE
Hover debug pane on top of game

### PR DESCRIPTION
**Pull request by philihp**
* Changes the styling of the debug pane so it doesn't reposition elements on the screen, and instead floats on top of them.

* Adds `jest-cli`, which was necessary to commit and run tests -- but i'm guessing everyone probably globally installed it, so it was never an issue.

## Before 
before mp4

## After
after mp4

### CODE REVIEW

**Comment by Stefan-Hanke** [comment]
How did you run the tests? Using `npm run test`, it should just work, since `jest` is available as command inside `node_modules/.bin`.

**Comment by Felizardo** [comment]
That looks good :)

**Comment by nicolodavis** [comment]
Looks great! Tests should run fine without `jest-cli` (if you use `npm test`), so can you check if that works and just include the CSS change in this PR?

**Comment by philihp** [comment]
Hmmm, jest-cli thing won't happen again after cleaning node_modules. Removing...

**Pull request merged**
