### PR TITLE
Correct import typo in multiplayer docs

### PR DESCRIPTION
**Pull request by zwliew**
#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x] Test coverage is 100% (or you have a story for why it's ok).

### CODE REVIEW

**Comment by nicolodavis** [comment]
Thanks!

**Comment by nicolodavis** [comment]
Just curious, was everything else working for you? There is a discussion at https://github.com/google/boardgame.io/issues/138 about some parts of the docs that aren't working for some people.

**Comment by zwliew** [comment]
Yep, it all works fine for me. Admittedly, I set up and configured Babel a little differently and I hadn't tried running the Client and the Server on the same Node server.

**Comment by zwliew** [comment]
I do think that the very first part (adding 'multiplayer: true') should be placed after the part on setting up a separate server though.

**Pull request merged**
