### PR TITLE
Make npm scripts cross platform

### PR DESCRIPTION
**Pull request by RobertSandu**

### CODE REVIEW

**Comment by nicolodavis** [comment]
This is very useful. Thank you!

Will take a look soon.

**Comment by nicolodavis** [comment]
Please sync your branch so that it applies cleanly on master and I can merge.

**Comment by RobertSandu** [comment]
Done

**Comment by RobertSandu** [comment]
I think I used another email for this commit. I signed a CLA for this email too. Is this ok?

**Comment by robert-sandu** [comment]
Ok, so now it should be ok. I commited from this account

**Comment by nicolodavis** [comment]
Not sure why the Travis stuff hasn't come back. Would you mind sending this again?

**Pull request closed without merging**
