### PR TITLE
Update jest

### PR DESCRIPTION
**Pull request by saeidalidadi**
I had issue with running tests so I did update jest. but the last change that helped me to fix the issue 
was adding test as environment variables and  `--no-cache` as jest options.
Also a I install a module that jest documentation has recommended [here ](https://facebook.github.io/jest/docs/en/getting-started.html#additional-configuration)

### CODE REVIEW

**Comment by nicolodavis** [comment]
What was the issue running tests before?

**Comment by saeidalidadi** [comment]
It was an error for all tests as:
```
SyntaxError: Unexpected token import
```

**Comment by nicolodavis** [comment]
Which version of Node are you running?

Just want to make sure this is absolutely necessary given that tests work fine on Travis and on my different setups.

**Comment by saeidalidadi** [comment]
I am running on `v8.9.3`.
I could test it on `v7` and `v8.1`

**Comment by saeidalidadi** [comment]
I checked the tests on `6.x`, `7.x` and `8.x` of node versions and all passed successfully.

**Comment by nicolodavis** [comment]
Great! Will get this in. Any idea why there are so many commits (even some that are already in).

**Comment by saeidalidadi** [comment]
I pulled all changes from upstream while I was working on the `update-jest` branch and I did not any `rebase`,  [this one](https://github.com/google/boardgame.io/pull/39/commits/12fdd58db6dc3ff22538860c00006a36e2ee57b9) is the mistake that shows this branch have been created from another branch which was behind master(not sure).
this is my workflow:
1. Pull from upstream.
2. Create a branch for new task.
3. Do changes.
4. Commit.
5. Pull from upstream.
6. Push to fork as a branch

**Pull request merged**
