### PR TITLE
Makes winner evaluation to be part of the Game API instead of being assumed to be in the state.

### PR DESCRIPTION
**Pull request by Felizardo**
This will be needed for implementing miniMax later per issue #7 , given that we need a standard way to know if the game is finished or not, and who won.

### CODE REVIEW

**Comment by Felizardo** [comment]
Wait, Im also a Google employee, I guess signing the CLA is redundant lol

**Comment by Felizardo** [comment]
Done, signed. I signed it!

**Comment by Felizardo** [comment]
@nicolodavis Let me know what you think about this change. I think there is other ways to do the same, but I think it is clearer to have it being part of the API.

We need some way of knowing that the game is over for the MiniMax, so the search can stop. In this case it would stop if winner() returns something other than null.

**Comment by Federkun** [comment]
Uhm, do you think there are use case where the winner won't be the current player of that turn? If not, we can avoid writing

```
winner: function(G, ctx, id)  {
    if (theOnlyThingThatIAmInterested(G)) {
         return ctx.currentPlayer;
   }
   return null;
 }
```

each time.

**Comment by nicolodavis** [comment]
Thanks for the PR @Felizardo! This looks mostly ready to be merged. I'll make a few changes closer to the weekend and get it in.

**Comment by Felizardo** [comment]
Hey Frederico,

That's definitely true for most of the simple games. However, in more
complex game rules you might do some action that leads someone else to win.
For instance, you might have hidden objectives of eliminating some player
and you win even if someone else does eliminate the player for you.
Leaving the function to decide who wins gives this flexibility.

**Pull request merged**
