### PR TITLE
React Native Client

### PR DESCRIPTION
**Pull request by chrisheninger**
## TODOs

- [x] Add ReactNativeClient
- [x] Fix errors that arose while building the demo
- [x] Convert tic-tac-toe example to RN app using expo.io + create-react-native-app 
- [x] Style tic-tac-toe
- [x] Upload demo to Expo https://expo.io/@chrisheninger/bgio-react-native-tic-tac-toe

FUTURE: Create an embeddable [Snack](https://snack.expo.io) for the boardgame.io website example section

-----

@nicolodavis so not much changed here– I moved the `client.css` from the raw client over to the react-specific client since that's where the `div`s are used.

Other than that– I ended up implementing it without using any react-native components. I've got a test repo that I used to import the client (see below).

I tinkered with actual tests but didn't have much luck. What I did try involved duplicating react.test.js, updating the board's divs to react-native's View and Text primitives– and then updated the jest preset to use react-native. I think the broke other things though... not sure what the proper way to go about this is. Happy to give it another stab when I have time– would love guidance if you've got any.

https://github.com/chrisheninger/bgio-react-native-client-test

It's working in an iOS simulator, but when I test on my Android (Pixel)– I'm getting an error ```undefined is not a function (evaluating 'phases[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')``` from core.js `FlowWithPhases` in `Game`.

### CODE REVIEW

**Comment by nicolodavis** [comment]
Ah, doesn't seem like there is an option that allows the sender to modify the labels!

I'll remove this recommendation from the guidelines.

**Comment by nicolodavis** [comment]
Sorry about the delay! Will take a look at this next week.

**Comment by nicolodavis** [comment]
I think it's [this line](https://github.com/google/boardgame.io/blob/master/src/core/flow.js#L226) that's not getting transpiled properly. I'm not sure why that's the case, but one option would be to just change the for...of loop to a conventional for loop.

**Comment by chrisheninger** [comment]
I haven't had a chance to dig in yet– thanks for taking a look. I'll give that a try when I get time (probably this coming weekend) and if it's all working correctly I'll post a link to a React-Native Tic-Tac-Toe in Expo.

Do you have thoughts on how to manage the demo for this as well as tests?

**Comment by nicolodavis** [comment]
I'm not familiar with the React-Native landscape, so need to do some reading before I can recommend how to demo stuff. I'm guessing there are emulators that we can embed on web pages?

As for tests, does Jest's react-native environment not take care of everything we need?

**Comment by scally** [comment]
I had a similar need for a RN client, so I forked off this branch and found there was an issue with multiplayer in RN. When `multiplayer: true` is set, the RN client throws string parsing errors constantly.

When I tracked that back, I found that socket.io's usual method of upgrading a polling connection doesn't work well in the RN environment, so I added a commit to allow the multiplayer client to have an option set to just use pure websockets intead of upgrading a longpoll. 

My (very early days) commit for it is here in case you find it useful:

https://github.com/scally/boardgame.io/pull/1/commits/70eeb1ec7c8006e03602700866e8cced1153bb40

**Comment by chrisheninger** [comment]
I've got an example app up and running in the `examples/react-native` directory– I left some steps in the README.

I had to make a few changes to get everything working– would love help implementing better solutions if you've got them.

- I changed the `for...of` loops in client.js and flow.js to normal `for` loops. (this was required to fix an Android issue caused by transpilation)
- I updated the react-native client's class name and export– I was running into weird issues with `RawClient` being undefined– removing the `import { Client as RawClient }` and not being fancy about it all fixed this. (I'd be happy to have a better understanding of why this is happening, and possibly update this *or* the React client for consistency)

I'm not sure how to properly link the `boardgame.io` package inside of the examples/react-native directory. The app runs fine and the (one) test works when you've got the package linked locally– but CI doesn't have that.

Sorry if this is a bit of word vomit– I feel like I'm really close to having the initial implementation in place– what I've done technically works. 😅

**Comment by scally** [comment]
@chrisheninger @nicolodavis I updated my branch with some more fixes for this RN client -- the version proposed here didn't pass through enhancers, and the multiplayer issue I mentioned before. Can those things be part of this PR, or should I submit a separate one after this lands?

**Comment by chrisheninger** [comment]
@scally looks like we were working on this at the same time. 😅 Hopefully my updates don't cause too much issue– everything non-multiplayer appears to be working with my latest.

I'll let @nicolodavis decide how we want to bring this all together– he's always the man with a plan :)

**Comment by scally** [comment]
@chrisheninger 

> I'm not sure how to properly link the boardgame.io package inside of the examples/react-native directory. The app runs fine and the (one) test works when you've got the package linked locally– but CI doesn't have that.

Did you try a local reference like:
```
"dependencies": {
    "bar": "file:../boardgame.io/dist"
  }
```

It would require a step beforehand to run the build beforehand, but it might work.

**Comment by nicolodavis** [comment]
Let's just use a Babel alias like the main repo does? I'll add that here.

This looks really exciting! Sorry about the delay in getting to this.

**Comment by nicolodavis** [comment]
How do you get your computer and phone on the same network? I tried tethering, but I still can't seem to get the app to run on Expo.

**Comment by jstacoder** [comment]
If you setup the repo, then do `npm install -g exp` then `exp start`, that worked for me.

**Comment by chrisheninger** [comment]
Babel alias is the exact thing I was looking for! Thanks both of you for providing solutions. 🙂 

Please feel free to rename/reorganize things @nicolodavis– I wasn't sure if just dumping a `react-native` directory in the `examples` folder was the preferred method but I wanted there to be some example / way to develop on the RN client locally.

Let me know if there is anything else you need from me. I want to go back and take a quick style-pass on the example tic-tac-toe app, but I'm hoping just having a working prototype is good for now.

**Comment by jstacoder** [comment]
@nicolodavis i forgot to mention, in case your not familiar with exp, when you run `exp start` it will give you a qr code that you can use to load the app with the expo app

**Comment by jstacoder** [comment]
and it looks like we could add the demo to the docs with: https://github.com/expo/snack-sdk

**Comment by chrisheninger** [comment]
I should have time this weekend. I'll get the TicTacToe demo cleaned up (and styled a little bit) and uploaded to Expo– after which I'll add a link to the readme/docs, as well as embed a Snack on the actual website.

**Comment by nicolodavis** [comment]
Needed https://github.com/google/boardgame.io/pull/128/commits/6d740b846ed58bfed5115cf14f3fa653d7aaa616 to make the example work for me. I think the Babel alias didn't quite cut it because the bundler wasn't able to find files outside the `examples/react-native` directory.

**Comment by chrisheninger** [comment]
I ran into the issue with the files outside the directory– thanks for providing a fix.

I pulled your latest with the rn-cli.config.js but now I am getting a different error:

screen shot 2018-03-31 at 12 11 56 pm

I have no idea why it's trying to pull in the `react` client package instead of `react-native`... nothing in the example app references that. 🤔

**Comment by chrisheninger** [comment]
Styled it a bit– demos available here:

https://expo.io/@chrisheninger/bgio-react-native-tic-tac-toe
https://expo.io/appetize-simulator?url=https://expo.io/@chrisheninger/bgio-react-native-tic-tac-toe

**Comment by nicolodavis** [comment]
@chrisheninger How does multiplayer (socket.io) work with React Native?

**Comment by chrisheninger** [comment]
I haven't ever worked with websockets + RN... but it looks like @scally was making some progress getting it working properly here: 

>This is for compatibility with React Native. Socket.io starts by long-polling and attempts to upgrade that connection into a websocket connection later. This approach causes errors to be thrown in a RN environment, so we allow the client of the Multiplayer component to disable the polling and use only websockets. This should be safe in a RN environment because RN now has websockets built-in, so upgrading a polling connection shouldn't be necessary.

https://github.com/scally/boardgame.io/commit/70eeb1ec7c8006e03602700866e8cced1153bb40

**Comment by chrisheninger** [comment]
I hadn't even thought of mobile and web playing together— that's freaking sweet and super exciting. 😁

Thanks for helping get this feature in place, I'm super excited for it to ship 🙂

**Comment by nicolodavis** [comment]
@chrisheninger Do you think you have time to add a Tutorial for React Native analogous to the Tutorial we have for React at the moment?

**Comment by chrisheninger** [comment]
Sure! If I can't get to it tomorrow, it'll be next weekend but I'd be happy to. 👍

**Pull request merged**
