### PR TITLE
Advanced Turn Order Example

### PR DESCRIPTION
**Pull request by Stefan-Hanke**
This PR adds an example for showcasing advanced turn order options.
Currently, it adds the option to change the action players.

This is NOT finished, I've pushed and created this PR in order to facilitate discussion. #154 

#### Checklist

* [x] Use a separate branch in your local repo (not `master`).
* [x]  Test coverage is 100% (or you have a story for why it's ok).

### CODE REVIEW

**Comment by nicolodavis** [comment]
How about we have the fields displayed just once (rather than once per player), and have the players be rendered as just boxes (with some color codes for the activePlayers and the currentPlayer)?

**Comment by Stefan-Hanke** [comment]
You ok with the buttons per players? My goal is to allow to manually play through that _Militia_ example.

**Comment by nicolodavis** [comment]
Sure! I was just looking for a more visual cue for the rest (rather than just writing down the fields).

Changing color, emboldening etc are all fine ways to use visual cues.

**Comment by Stefan-Hanke** [comment]
Somehow, using `events` and `moves` simultaneously does not work. I'd like to have the _Play Militia_ button to reduce actions to 0, and to modify `actionPlayers`.

**Comment by nicolodavis** [comment]
That's because **changeActionPlayers** loses the `stateID` [here](https://github.com/google/boardgame.io/blob/master/src/core/flow.js#L572). I have a fix for this that I will push soon.

**Comment by Stefan-Hanke** [comment]
The example is now working as intended.

**Pull request merged**
