### PR TITLE
WIP: feature: add timer

### PR DESCRIPTION
**Pull request by akaguny**
Hi! It's my first PR in this repository)
This feature was annonced in #92 
I have some problems with implementing this.
When timer does initialise, at what moment?
I think that it will be start of the turn, because timer it's about end turn additional condition, and another phases can have another timeouts for turns;

### CODE REVIEW

**Comment by akaguny** [comment]
about ci error: https://travis-ci.org/google/boardgame.io/builds/340089000#L576
need to upgrade jest to new minor version

**Comment by nicolodavis** [comment]
Yes, let's have two timers:
- `secondsPerTurn`
- `secondsPerPhase`

Can you update the Jest version in this PR as well?

**Comment by akaguny** [comment]
i was merged this with https://github.com/google/boardgame.io/pull/108

**Comment by akaguny** [comment]
i have alot of work and i want finish PR at the end of the week

**Comment by nicolodavis** [comment]
Take your time! No hurry.

**Comment by akaguny** [comment]
i have some problems with implementation:
i dont whant to call timer with callback as endPhase or endTurn actions, because in flow this functions must return actual updated state, but in my function i have not mechanism for modify or get actual state
timers is async and flow engine is sync, i do not have oppotunity for check time is out parameter
Soon after work i will push to repository my code work for discussion.

**Comment by nicolodavis** [comment]
@akaguny I'm not sure if you're waiting for me or the other way around. Sorry if you've been waiting for a comment! What's the status of this PR?

**Comment by akaguny** [comment]
pr is frosen =( alot of work and no time.
i`m close the PR, because maybe anybody want to get the feature but saw the pr =)

**Comment by nicolodavis** [comment]
OK no problem! Feel free to re-open it if you pick it up in the future. Maybe I'll get to it if I have some time soon as well.

**Pull request closed without merging**
