### PR TITLE
Update license year

### PR DESCRIPTION
**Pull request by benhc123**

### CODE REVIEW

**Comment by nicolodavis** [comment]
This is unnecessary. The year is the year of first publication.

**Comment by benhc123** [comment]
@nicolodavis, technically it's the year of last modification to the copyrighted article (in this case the repository).

**Comment by dentemple** [comment]
Technically, a copyright notice isn't necessary at all.  Copyright is granted automatically if it's applicable to the work.

**Comment by benhc123** [comment]
@dentemple You're right that copyright is often implied. But if you have a file called `LICENSE`, updating it seems reasonable. In many cases having a notice like this is a representation of the fact that you have made an effort to enforce that copyright.

**Pull request closed without merging**
