### PR TITLE
Sedobrengocce/feature.timer

### PR DESCRIPTION
**Pull request by sedobrengocce**
#### Checklist

* [ x ] Use a separate branch in your local repo (not `master`).
* [ x ] Test coverage is 100% (or you have a story for why it's ok).

But I need to improve my tests

### CODE REVIEW

**Comment by sedobrengocce** [comment]
double checked, signed with this account, can someone help me?

**Comment by sladwig** [comment]
I think the bot complains because there are commits by Giuseppe Tofu, for whom I suspect the bot can't find an agreement.

**Comment by sedobrengocce** [comment]
i specified my realname and github username in cla

**Comment by sladwig** [comment]
did you also specified the email adress of the other commits in your cla?

**Comment by sedobrengocce** [comment]
yes, same as github

**Comment by sladwig** [comment]
just to be sure: I just checked the comits there are two email adressed used @gmail.com and @blastinnews. As I understand it both need to be in the cla...

**Comment by nicolodavis** [comment]
Also, I'm not sure why there are 250+ commits in this branch. Possibly a bad merge?

**Comment by sedobrengocce** [comment]
I changed mail using filter but doesn't work as aspected.
I'll close this one and open a clean new one

**Pull request closed without merging**
